modLoader = "javafml"
loaderVersion = "*"
license = "GNU General Public License 3.0, https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL = "${contact_issues}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
versionRange = "${mc_version_range}"
mandatory = true

[[dependencies.${mod_id}]]
modId = "cloth_config"
versionRange = "${mods_clothconfig_range}"
mandatory = true